### ISSUE TITLE
Checkpoint Implementation

### ISSUE THREAD

**Issue by adityabandla** [bbuchfink/diamond#128]
Hi Benjamin

Is it possible to implement a checkpoint at different stages of a diamond run? It would be easier to restart from the checkpoint again, if for some reason the current run gets aborted, rather than starting afresh

Best,
Aditya

**Comment by bbuchfink** [comment]
Hi,

it would be a useful feature, but not that easy to implement. There are
other priorities at the moment so I don't think it'll be done in the near
future.

Best regards,

Benjamin

**Comment by adityabandla** [comment]
Thanks Benjamin!

**Comment by slambrechts** [comment]
Sorry for asking this question again, but does diamond start afresh everytime it gets aborted, or has checkpointing been implemented in the meantime? I'm asking because I'm running out of time on our cluster (maximum runtime 72 hours). Alternatively, does increasing the `-b` block size parameter improve speed?

**Comment by bbuchfink** [comment]
It has been implemented, but only in multiprocessing mode, see here: https://github.com/bbuchfink/diamond/wiki/6.-Distributed-computing

Yes, increasing `-b` does improve speed, up to a point.

**Comment by slambrechts** [comment]
ok interesting, thanks
