### ISSUE TITLE
Reporting very short hits 

### ISSUE THREAD

**Issue by Wanderingstefan** [bbuchfink/diamond#171]
Hey, 

I am using diamond to blast a multifasta file against a .dmnd database version of itself. I would expect to get a hit for every query sequence and no unaligned sequences. However, I get some unaligned sequences, very short ones (6-12 aa). Is there any filtering option defaulted in diamond that prevents reporting of those hits? I am running diamond like this:

'diamond blastp -q query_file.fa -p 24 -d query_file.dmnd -o out.txt --more-sensitive --id 100 --query-cover 100 --max-target-seqs 1 --subject-cover 100 --hit-score 0 --un unaligned.txt -f 6 qseqid sseqid evalue score stitle slen pident length qlen qseq'

The fasta file and the corresponding .dmnd database contain exactly the same sequences, so my only explanation for unaligned sequences would be diamond not reporting them. Do you have any idea what the issue could be?

Thanks for your reply!

**Comment by bbuchfink** [comment]
Hi,

note that --hit-score sets a score cutoff for the first filter stage. For
the final reporting, the parameter is --min-score. So the first reason the
hits don't get reported is that their e-value is above 0.001.

But if you want to get Diamond to work for these very short hits, you will
have to change a number of parameters because there are several internal
filtering stages. Also the normal seed configuration will never find hits
shorter than 10aa because the shortest seed is 1011110111. It is possible
to change that on the command line as well.

**Comment by Wanderingstefan** [comment]
Hej, 

Thanks for your fast reply and sorry for my late one! Replaced --hit-score with --min-score, but I don't see how to change the seed size, could you instruct me how to do it?

**Comment by bbuchfink** [comment]
The option is like --shape-mask 11111
That would use one seed of length 5. But I must warn you, the performance
will be reduced a lot with settings like this. Diamond was not really
designed for these very short alignments.

**Comment by Wanderingstefan** [comment]
Yes, I see that the performance is reduced, I guess I have to find another way to do what I want. 
Thank you very much for your help!

All the best!
