### ISSUE TITLE
too slow on Loading reference sequences...

### ISSUE THREAD

**Issue by jingzhejiang** [bbuchfink/diamond#185]
Hi,

I'm running diamond on AWS EC2, using NCBI's NR as a reference database.
But when i start to run blastx, it usually takes hundreds to thousands of seconds to Loading reference sequences... again and again. No matter which parameters (--block-size, --index-chunks, --threads, --outfmt) are combined.
It feels like most of the time were wasted at Loading step, even when I was blasting only 9.5 Mb query data on a 128 core instance, against a 81 Gb reference (nr.dmnd) .

I query the support, they told me there were no I/O problem or any other hardware failure to my instance. 
So, what is the problem?

Thank you! Waiting for your reply. 
Wish you a Happy Holiday!

Jingzhe

**Comment by bbuchfink** [comment]
Hi,

I'd like to try and reproduce this problem on AWS EC2. Can you please tell
me how you setup your instance, particularly how you configured your
storage options and where you put the database file.

Best regards,

Benjamin

**Comment by guignonv** [comment]
Hi! This issue has been closed 10 days ago but I ran into the same problem.

I have a 75Gb ".dmnd" Diamond bank made on protein sequences from RefSeq (https://ftp.ncbi.nlm.nih.gov/refseq/) to scan all RefSeq sequences and find any match in any reign. Basically, in my case, the idea behind that is to see if a plant gene could be found in other non-plant genomes. Diamond takes several hours to load the bank for a simple search of a couple of sequences. I run it on a cluster with a lot of memory (I even tryed --block-size 14 as we got more than 100Gb RAM) but still it is "too long" to load. We also have a performant file system.

I tryed to split the big database in pieces. Some are 4-5Gb and still takes a couple of minutes to load for a single scan.

I guess there is no magical solution: these are big databases and will take time to load/preprocess anyway. But I have a though: would it be complicated to create a "daemon service mode" for Diamond making it load a database once, stay in memory (until the daemon is killed) and process queries on demand (from an input port and output results in a file specified by the query)? The idea would be to spend the hours of loading only one time and then, I could send to that daemon my series of FASTA (several 10 of thouthands!) to scan. Otherwise, I can't use Diamond for that task as it would take more than a year of computation! :-s

Let me know how complicated such a task would be, regarding how the code is currently structured.

**Comment by bbuchfink** [comment]
If I understand this issue correctly, the whole run of Diamond is what takes a couple of hours, not just the loading of the database? Or does it take this long for when `Loading reference sequences...` is being displayed?

If the whole run takes this long, it is a limitation of the algorithm which is designed towards large query files, and is not very efficient if you only input a couple of sequences. You can try to use the option `--algo 1` which may help to speed this up. Still, Diamond is not ideal for this small-query scenario. I plan to improve this situation, but this is probably still going to take some time. Of course it would be best if you could concatenate your FASTA files into a larger chunk.

**Comment by guignonv** [comment]
Apologies for taking so long to answer, I did not expect an answer here since the issue was closed. I was just giving a suggestion. :-)
Thank you very much for your answer and your suggestions. Unfortunately, for several reasons, I can't try `--algo 1` now but maybe in a couple of month... :-s (subventions issues and cluster issues as well). However, I can confirm it was showing "`Loading reference sequences...`" forever and was not starting any search process yet. I believed it was processing the several gigabytes of bank data to load. That's why I thought it would have been nice to load the bank once with a daemon. Then the daemon would wait for queries sent by another process. But I don't know how diamond algorithm is built and maybe, it couldn't work that way? Maybe it requires the query sequence first? :-s

Anyway, if it was possible then, I was thinking of something like:
`diamond makedb  --in THE_100G_FASTA.fasta  -d THE_BIG_DATABASE
diamond startdaemon  -d THE_BIG_DATABASE  --port  81457
(several minutes/hours to load)
diamond blastp --server localhost  --port 81457  -q query.faa  -o matches.m8
diamond blastp --server localhost  --port 81457  -q query2.faa  -o matches.m8
diamond blastp --server localhost  --port 81457  -q query3.faa  -o matches.m8
...
diamond stopdaemon  --port  81457`

But once again, it is a naive though as I don't know if it could work that way and if queries could be efficient enough with such a big database.

**Comment by bbuchfink** [comment]
It would be possible to cache the database in memory using a daemon process. The efficiency of single-query searches would still be limited by the runtime generation of the index, which is too large to be simply kept in memory.

There is a release upcoming which has some optimizations for small query files, including to cache the database in memory using memory mapped files. You should probably try if this improves your problem.
