### ISSUE TITLE
Invalid taxonomy mapping file format

### ISSUE THREAD

**Issue by DarrenObbard** [bbuchfink/diamond#215]
Hi, 

When making a database with taxonomy information using prot.accession2taxid.gz all works fine. 

However, I wish to make a database from TSA sequences that I have translated. I assumed that I could simply use nucl_wgs.accession2taxid.gz in place of prot.accession2taxid.gz because (as far as I can see) the format is identical. But I get the error "Invalid taxonomy mapping file format"

Any suggestions as to why, or what a workaround might be?

Thanks,

Darren

**Comment by bbuchfink** [comment]
Hi Darren,

I suspect that is due to an accession being too long in that file. I plan
to get rid of this restriction. However if you do need a workaround right
now, you need to edit the source code to allow longer accessions.

In the file data\taxonomy.cpp, look for the string "%*s%15s%u%*u" in line
61 and change 15 to something else (like 20).
In data\taxonomy.h at line 41 change max_accesion_len to the same number.

Then compile the software and see if that works.

Best regards,

Benjamin

**Comment by sejmodha** [comment]
Hi There,

I am facing the same issue with the newer versions of the prot.accession2taxid. 
Any suggestions on how to fix this when diamond is installed through conda?

**Comment by bbuchfink** [comment]
Sorry I didn't see this earlier. Please try compiling the latest master branch from my repository for correcting this.

**Comment by qiyunzhu** [comment]
Same here. Version 2.0.6 from Conda still has this issue. I am using custom reference sequence IDs (such as "NODE_123_Length_456_Prodigal_789" which are long and do not contain a dot version number suffix. What will be the best strategy to get around this?

**Comment by bbuchfink** [comment]
Try to clone the repository, edit `data/taxonomy.h:47`, increase `max_accesion_len` to a larger number and compile from source.

**Comment by qiyunzhu** [comment]
@bbuchfink Thank you for your quick response. I have tried this recipe and everything worked in my case.
