### ISSUE TITLE
xml in blast2go: No content in table

### ISSUE THREAD

**Issue by jfordonez** [bbuchfink/diamond#239]
Hi,

B2G could not read the diamond-generated xml file fed to it. It only says "no content in table"

I'm using diamond 0.9.22 and blast2go 5.2.4

diamond command:
diamond blastx -d ~/Documents/Database/DIAMOND_uniref90/uniref90 -q ../04
_Trinity_Assembly/trinity_out_dir.Trinity.fasta -o uniref90.blastx.v2.xml -p 12 -k 1 -c 6 --sensitive -b 5 -f 5 --salltitles

I wonder if this is because I used uniref90 as database? Thank for the help!

June

**Comment by bbuchfink** [comment]
Hi June,

I don't know Blast2go very well and I'm not sure what the problem there is.
You could try to align your contigs against another database like
SwissProt, and see if that works. To check if it's a problem with the
output format, you can also try to align a small portion of your data
against UniRef90 using BLAST instead of Diamond.

Best regards,

Benjamin

**Comment by jfordonez** [comment]
Hello Benjamin,

I tried BLAST's blastx with nr and SwissProt but none of these seemed to display any information in B2G but I'm still getting the "No content in table." I also used the online blastx and downloaded the xml output but still no luck. So I guess the issues is with B2G formatting. May I request for an xml file that worked with B2G in you case? Thank you!

J

**Comment by bbuchfink** [comment]
Hi June,

sorry for the very late reply. I'm not really qualified to provide support
for Blast2go. I did try to align a small file against SwissProt using
Diamond and import the results into Blast2go. Using Blast2go version 5.2.4,
I used File->Load->Load Blast results->Load Blast XML (Legacy) and this
seemed to work for me.
