### ISSUE TITLE
Make format 6 --unal 1 output include qseq

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#255]
When you use something like bowtie2 or bwa to do nucleotide alignments, you get a SAM file that you can post-process to extract queries that were unmapped (`samtools -F 4 fastq FILE.sam`). This is very useful in processing where you want to throw away reads that map to the host genome if you're looking for something else (e.g., bacterial or viral reads).

I'd like to be able to do the same with DIAMOND. I can run e.g. `diamond blastx --unal 1 -outfmt 6 qtitle qseq qqual stitle` and look for the subject title being `*`.  But the query sequence is printed as a `*` (the quality string is printed correctly).

Tons of I/O could be removed in a case like this if `--noal` was available, to simply not print the aligned queries.

Thanks Benjamin :-)  I do know I should just write some of this myself.....

**Comment by bbuchfink** [comment]
Since qseq refers to the aligned part of the query sequence, this being
printed as * for unaligned queries works correctly. But I will add the
full_qseq field for this purpose.

There is already the --un option to write unaligned queries to a file, and
you can redirect the main output to /dev/null if you don't need it. But it
would be more efficient internally to turn off the generation of the output
(which can actually already be done using the undocumented option -f null).

**Comment by terrycojones** [comment]
OK, yes, makes sense re `full_qseq`. Thanks for the explanation. I'll close this.
