### ISSUE TITLE
issue with -e evalue

### ISSUE THREAD

**Issue by TomhitsJerry** [bbuchfink/diamond#268]
1.diamond blastx -p 8 -sensitive -f 6 -d db -q non-redundant-nucl.fasta -o blast.out -t /dev/shm -e 0.00001
2.diamond blastx -p 8 -sensitive -f 6 -d db -q non-redundant-nucl.fasta -o blast.out -t /dev/shm  
    and then awk' $11<=0.00001' >last.blast
Question:
   why result1 is less than result2?(not the same)

and also the same situation as --id .
3.diamond blastx -p 8 -sensitive -f 6 -d db -q non-redundant-nucl.fasta -o blast.out -t /dev/shm
awk '$3>=50' > last.out
4.diamond blastx -p 8 -sensitive -f 6 -d db -q non-redundant-nucl.fasta -o blast.out -t /dev/shm --id 50
result3 is less than result4 (not the same).

Thanks!

**Comment by bbuchfink** [comment]
The e-value parameter of Diamond does not only control the output, it also affects the algorithm. It is used by some internal heuristics for ranking hits before final alignments are computed so you can't expect to get exactly the same results.

In the second case, since Diamond outputs the 25 best alignments per query by default, filtering by id% afterwards will miss some alignments that come after the filtered alignments if Diamond does the filtering, since it will still try to report 25 alignments. Try using the option -k0 to report all hits.

**Comment by TomhitsJerry** [comment]
Thanks for your help.
And while I am trying to figure out this, i use blast+/blastx. By default, blastx outputs 500 best alignments per query. And in the meanwhile , i use diamond -k 500.
Result:
blastx has 271797 alignment ；diamond has 179358 .

Question:
Does the result normal?  and why?


Thanks a lot!

**Comment by bbuchfink** [comment]
You also need to make sure that you use the same e-value cutoff for both tools (BLAST default is 10). Still the e-values of Diamond are not exactly the same, which could be one reason.

Another is the more aggressive low complexity masking used by Diamond (you can turn it off using `--masking 0`).

Also, Diamond is not as sensitive as BLAST, so you will get less hits.
