### ISSUE TITLE
Different alignments from different lengths of query sequence

### ISSUE THREAD

**Issue by jiwoongbio** [bbuchfink/diamond#299]
Can you please check the following two query alignments? The first query is exactly identical with the database sequence. The second one is longer than the first one and has extra upstream sequence. They provide different alignments.

**Database sequence:**
MRTILAALAVLAGLATMPAAAQSTSGLSISSRVAAAEAAEAAARSKAPAPSAQAPAIPEPASIVLPVPAVAIYPGDTISDSMLVDRAYSVSPSDRVAVATSRQALIGKVARRGLQAGTPIPVNAYADPQVVSRGHLAPVVLQEGGLTISGFAMAMEDGSVGKIVRLKNLDSGLIIAGTVQSDGSVRVSGQ

**1. Query sequence:**
MRTILAALAVLAGLATMPAAAQSTSGLSISSRVAAAEAAEAAARSKAPAPSAQAPAIPEPASIVLPVPAVAIYPGDTISDSMLVDRAYSVSPSDRVAVATSRQALIGKVARRGLQAGTPIPVNAYADPQVVSRGHLAPVVLQEGGLTISGFAMAMEDGSVGKIVRLKNLDSGLIIAGTVQSDGSVRVSGQ
**Output alignment:**
MRTILAALAVLAGLATMPAAAQSTSGXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXVAIYPGDTISDSMLVDRAYSVSPSDRVAVATSRQALIGKVARRGLQAGTPIPVNAYADPQVVSRGHLAPVVLQEGGLTISGFAMAMEDGSVGKIVRLKNLDSGLIIAGTVQSDGSVRVSGQ

**2. Query sequence:**
LRSPHHESTRYRRNRHECPADERGSDREQHREHQHDRLQAGPRRILRPALPVRAHPGHPEPRRRPGDSGRRDARPRRPHGWHPQPAHPGPADPDRQHARSRGQRPRHVRDHHAGRPDGLYPRGLVQPQRDGPARHLGRLCDQPGDPVPEQRHGDPGQRERAGLCDHPEPDQSAAPRPAHARELRQRVRHGAARQQPLSRDTRVWPADRRRCRRRGLRQDPAGLPRGVQRRSGEGNHRADRRPALLRDELQGDPGRRRNVEDRLHRHPLTARAVSSIKDTRAAMRTILAALAVLAGLATMPAAAQSTSGLSISSRVAAAEAAEAAARSKAPAPSAQAPAIPEPASIVLPVPAVAIYPGDTISDSMLVDRAYSVSPSDRVAVATSRQALIGKVARRGLQAGTPIPVNAYADPQVVSRGHLAPVVLQEGGLTISGFAMAMEDGSVGKIVRLKNLDSGLIIAGTVQSDGSVRVSGQ
**Output alignment:**
VAIYPGDTISDSMLVDRAYSVSPSDRVAVATSRQALIGKVARRGLQAGTPIPVNAYADPQVVSRGHLAPVVLQEGGLTISGFAMAMEDGSVGKIVRLKNLDSGLIIAGTVQSDGSVRVSGQ

**Comment by jiwoongbio** [comment]
The testing version is "diamond version 0.9.25"

**Comment by bbuchfink** [comment]
It's because of the repeat masking, a larger party of the query is masked. You can view the masking by building a database and then using `diamond getseq`:

`>2
LRSPHHESTRYRRNRHECPADERGSDREQHREHQHDRLQAGPRRILRPALPVRAHPGHPEPRRRPGDSGRRDARPRRPHGwhpqpahpgpadpdrqharsrgqrprhvrdhhaGRPDGLYPRGLVQPQRDGPARHLGRLCDQPGDPVPEQRHGDPGQRERAGLCDHPEPDQSAAPRPAHARELRQRVRHGAARQQPLSRDTRVWPADRRRCRRRGLRQDPAGLPRGVQRRSGEGNHRADRRPALLRDELQGDPGRRRNVEDRLHRHPLTARAVSSIKDTRAAMRTILAALAvlaglatmpaaaqstsglsissrvaaaeaaeaaarskapapsaqapaipepasivlpvpaVAIYPGDTISDSMLVDRAYSVSPSDRVAVATSRQALIGKVARRGLQAGTPIPVNAYADPQVVSRGHLAPVVLQEGGLTISGFAMAMEDGSVGKIVRLKNLDSGLIIAGTVQSDGSVRVSGQ`

The masking can be turned off by `--masking 0` if you prefer.
