### ISSUE TITLE
Parallel Scalability

### ISSUE THREAD

**Issue by davidemms** [bbuchfink/diamond#321]
Hi

Do you happen to have any figures on the parallelisation efficiency of diamond blastp/blastx?

Many thanks
David

**Comment by bbuchfink** [comment]
Hi David,

no, sorry but I never conducted any explicit benchmarks for this.

Benjamin

**Comment by davidemms** [comment]
Hi Benjamin

No worries, thanks for the quick response. I can do some testing myself to work out what works best for my workflow.

All the best
David

**Comment by bbuchfink** [comment]
If your question is whether to run one instance of Diamond on a node using all cores, or run multiple instances with fewer threads each, the first option is clearly better. That's because you will have more memory for a single job, which permits to increase the `-b` option and decrease the `-c` option which will improve efficiency.
