### ISSUE TITLE
Error running blastp file

### ISSUE THREAD

**Issue by shravya-thatipally** [bbuchfink/diamond#63]
Hello,
I tried to execute blastp command as shown below , its appending .dmnd at the end of database.

user@s:~/diamond-0.8.17/bin$ ./diamond blastp -d /home/shravya1thatipally/DiamondData/humanDB/db -q /home/shravya1thatipally/DiamondData/chimpGenome.transcripts.fa -o humanfastachimpdb.xml
diamond v0.8.17.79 | by Benjamin Buchfink buchfink@gmail.com
Check http://github.com/bbuchfink/diamond for updates.
# CPU threads: 48

Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
# Target sequences to report alignments for: 25

Temporary directory: 
Opening the database...  [0.000113s]
Error: Error opening file /home/shravya1thatipally/DiamondData/humanDB/db.pin.dmnd

Also , I tried giving no auto append 
user@s:~/diamond-0.8.17/bin$ ./diamond blastp -d /home/shravya1thatipally/DiamondData/humanDB/db -q /home/shravya1thatipally/DiamondData/chimpGenome.transcripts.fa --no-auto-append -o humanfastachimpdb.xml
diamond v0.8.17.79 | by Benjamin Buchfink buchfink@gmail.com
Check http://github.com/bbuchfink/diamond for updates.
# CPU threads: 48

Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
# Target sequences to report alignments for: 25

Temporary directory: 
Opening the database...  [0.000116s]
Error: Error opening file /home/shravya1thatipally/DiamondData/humanDB/db

Actually db location has three diamond db files and i am trying to give all the three files but it is not working.Can someone please help in resolving the above issue?

Thanks in advance.

**Comment by bbuchfink** [comment]
What are the actual file names? Can you run `ll /home/shravya1thatipally/DiamondData/humanDB/` and show me the result?

**Comment by shravya1thatipally** [comment]
shravya1thatipally@feynman:~/diamond-0.8.17/bin$ ./diamond blastp -d /home/shravya1thatipally/DiamondData/humanDB -q /home/shravya1thatipally/DiamondData/chimpGenome.transcripts.fa  -o humanfastachimpdb.tab
diamond v0.8.17.79 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 48
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 25
Temporary directory: 
Opening the database...  [0.000124s]
Error: Error opening file /home/shravya1thatipally/DiamondData/humanDB.dmnd

**Comment by bbuchfink** [comment]
No, I meant to show me the content of this directory by running the `ll` command, not diamond.

**Comment by shravya1thatipally** [comment]
shravya1thatipally@feynman:~/DiamondData/humanDB$ ll
total 132660
drwxrwxr-x 2 laraib laraib      4096 Aug  2 15:12 ./
drwxrwxr-x 4 laraib laraib      4096 Aug  2 15:13 ../
-rw-rw-r-- 1 laraib laraib  16973488 Aug  2 15:12 db.phr
-rw-rw-r-- 1 laraib laraib    859248 Aug  2 15:12 db.pin
-rw-rw-r-- 1 laraib laraib 117996216 Aug  2 15:12 db.psq

I  created another DB again but even that is not working:
shravya1thatipally@feynman:~/diamond-0.8.17/bin$ ./diamond blastp -d
humandb -q /home/shravya1thatipally/DiamondData/chimpGenome.transcripts.fa
-o humanfastachimpdb.tab
diamond v0.8.17.79 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 48
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 25
Temporary directory:
Opening the database...  [3.9e-05s]
Opening the input file...  [0.001517s]
Opening the output file...  [0.000104s]
Loading query sequences...  [13.4342s]
Building query histograms...  [2.45012s]
Allocating buffers...  [0.002292s]
Loading reference sequences...  [13.9135s]
Building reference histograms...  [1.44741s]
Allocating buffers...  [0.002742s]
Initializing temporary storage...  [0.003468s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [7.22627s]
Building query index...  [5.46894s]
Building seed filter...  [1.87898s]
Searching alignments... terminate called after throwing an instance of
'File_write_exception'
  what():  Error writing file diamond-57ad1b12-2d.tmp. Disk full?
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
Aborted (core dumped)

Is it because of size constraint?

**Comment by bbuchfink** [comment]
Telling from the file extensions, these look like blast database files, which you cannot use for diamond. You need to use `diamond makedb` to create a diamond database from a fasta file, which will have the dmnd extension. Although it looks like you did that now if the program ran that far. This error message means that the program could not write to the output directory. Could you have run out of disk space or disk quota?

**Comment by shravya1thatipally** [comment]
df -hT /home
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/sda4      ext4  3.4T  3.1T  139G  96% /
There is still 139 GB available will that be enough?

**Comment by bbuchfink** [comment]
That should certainly be enough. For some reason it can't write to that directory, unfortunately I don't know how this could happen.

**Comment by hjdong** [comment]
> That should certainly be enough. For some reason it can't write to that directory, unfortunately I don't know how this could happen.

I had the same problem of the 0.8.22 version，I don't know how this could happen
