### ISSUE TITLE
Error while using view on daa file made with custom matrix

### ISSUE THREAD

**Issue by mlirski** [bbuchfink/diamond#70]
Hello,
I've taken advantage of the new diamond functionality and aligned my reads using VTML200 scoring matrix with following parameters: gapopen: 15, gapextend 1.5, lambda 0.318, K 0.13.
I've successfully meganized the file and analyzed it in megan.
Now I wanted to extract some alignment stats, draw histograms, etc. yet when I try to use diamond view i get the following error:
Error: Invalid gap open and/or gap extend scores.
The only uncommon thing that I've done with this file is that I copied it while it was open in MEGAN and data was being exported to csv file.
Could this be a reaston for the error, or it's just a bug?
Thank you in advance,
Maciej

**Comment by bbuchfink** [comment]
Sorry, I should have said that somewhere. The custom scoring matrices don't yet work together with the DAA format, because storing the extra info would require changes to the format. I can provide a quick fix for diamond view by allowing the scoring parameters to be provided again on the command line.

**Comment by mlirski** [comment]
Thanks! That'd be great! Your previous fix worked like charm, thanks to you I get >90% good scoring alignments instead of ~50% I was gettiong when using BLOSUM series.

**Comment by bbuchfink** [comment]
Should be fixed in the latest release.
